name: ALG-CPT02

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: g++ -std=c++14 -O2 ALG-CPT02/r0.cpp -o main
    - name: geninput
      run: cmd /C echo 16384 > data.in
    - name: run
      run: cmd /C 'main < data.in'
